name: Go Tests
# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.16', '1.15', '1.14', '1.13' ]
    name: Go ${{ matrix.go }} test
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go test
