name: Go Tests

# Controls when the action will run. 
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.16', '1.15']
        k3s: ['v1.20.0+k3s2', 'v1.19.11+k3s1', 'v1.21.1+k3s1']
    name: Go ${{ matrix.go }} test k3s ${{ matrix.k3s }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Cluster
        uses: jupyterhub/action-k3s-helm@v1
        with:
          k3s-version: ${{matrix.k3s}}
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go test
